# Generated by Django 5.2.1 on 2025-05-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
