# Generated by Django 5.2.1 on 2025-05-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_property_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('land', 'Land')], max_length=50),
        ),
    ]
