# Generated by Django 5.2.1 on 2025-05-18 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Street address of the property', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Primary display image', null=True, upload_to='property_images/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Additional property images', upload_to='property_images/%Y/%m/%d/')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sorting order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='listings.property')),
            ],
            options={
                'verbose_name_plural': 'Property Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
